"use client"

import type React from "react"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Avatar } from "@/components/ui/avatar"
import { Sparkles, Send, Menu, Plus, User, Settings, LogOut } from "lucide-react"
import { cn } from "@/lib/utils"
import { ThemeToggle } from "@/components/theme-toggle"
import { SettingsDialog } from "@/components/settings-dialog"

type Message = {
  id: string
  content: string
  role: "user" | "assistant"
  timestamp: Date
  isTyping?: boolean
}

// Add this array near the top of the file, after the Message type definition
const suggestions = [
  "Tell me a joke",
  "Explain quantum computing",
  "Write a poem",
  "Help me debug my code",
  "Translate to Spanish",
]

export default function ChatInterface() {
  const [input, setInput] = useState("")
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      content: "Hello! How can I help you today?",
      role: "assistant",
      timestamp: new Date(),
    },
  ])
  const [isLoading, setIsLoading] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(typeof window !== "undefined" ? window.innerWidth >= 768 : true)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const [showSettings, setShowSettings] = useState(false)

  const simulateTyping = (message: string, messageId: string) => {
    let currentText = ""
    const words = message.split(" ")

    const typeWord = (wordIndex: number) => {
      if (wordIndex < words.length) {
        currentText += (wordIndex > 0 ? " " : "") + words[wordIndex]
        setMessages((prev) =>
          prev.map((msg) => (msg.id === messageId ? { ...msg, content: currentText, isTyping: true } : msg)),
        )

        // Consistent delay between words (80ms)
        setTimeout(() => typeWord(wordIndex + 1), 80)
      } else {
        setMessages((prev) =>
          prev.map((msg) => (msg.id === messageId ? { ...msg, content: currentText, isTyping: false } : msg)),
        )
      }
    }

    typeWord(0)
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isLoading) return

    const userMessage: Message = {
      id: Date.now().toString(),
      content: input,
      role: "user",
      timestamp: new Date(),
    }
    setMessages((prev) => [...prev, userMessage])
    setInput("")
    setIsLoading(true)

    // Add loading message immediately
    const loadingId = (Date.now() + 1).toString()
    setMessages((prev) => [
      ...prev,
      {
        id: loadingId,
        content: "",
        role: "assistant",
        timestamp: new Date(),
        isTyping: true,
      },
    ])

    // Simulate AI response after a delay
    setTimeout(() => {
      const response = "This is a simulated response. In a real application, this would be generated by an AI model."
      simulateTyping(response, loadingId)
      setIsLoading(false)
    }, 1500)
  }

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [])

  useEffect(() => {
    const handleResize = () => {
      setSidebarOpen(window.innerWidth >= 768)
    }

    window.addEventListener("resize", handleResize)
    return () => window.removeEventListener("resize", handleResize)
  }, [])

  const renderMessageContent = (message: Message) => {
    if (message.role === "assistant" && message.isTyping && message.content === "") {
      return (
        <div className="flex space-x-1">
          <div className="h-2 w-2 animate-bounce rounded-full bg-primary" style={{ animationDelay: "0ms" }}></div>
          <div className="h-2 w-2 animate-bounce rounded-full bg-primary" style={{ animationDelay: "150ms" }}></div>
          <div className="h-2 w-2 animate-bounce rounded-full bg-primary" style={{ animationDelay: "300ms" }}></div>
        </div>
      )
    }

    return (
      <div className={message.isTyping ? "relative" : ""}>
        {message.content}
        {message.isTyping && <span className="absolute -right-1 inline-block animate-cursor-blink">▋</span>}
      </div>
    )
  }

  return (
    <div className="flex h-screen bg-tertiary/20 dark:bg-dark-bg transition-colors duration-300">
      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 backdrop-blur-sm z-40 md:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}
      {/* Sidebar */}
      <div
        className={cn(
          "fixed inset-y-0 left-0 z-50 w-64 transform bg-light-bg shadow-lg transition-all duration-300 ease-in-out dark:bg-dark-bg dark:border-r dark:border-secondary/20 md:relative md:translate-x-0",
          sidebarOpen ? "translate-x-0" : "-translate-x-full",
          "md:static",
        )}
      >
        <div className="flex h-full flex-col">
          {/* New Chat Button */}
          <div className="p-4">
            <Button className="w-full justify-start gap-2 bg-primary text-primary-foreground hover:bg-primary/90 transition-all duration-300 hover:scale-[1.02]">
              <Plus size={16} />
              New Chat
            </Button>
          </div>

          {/* Chat History */}
          <div className="flex-1 overflow-y-auto p-2">
            <div className="mb-2 px-2 text-xs font-medium text-secondary/60 dark:text-tertiary/60">Today</div>
            <Button
              variant="ghost"
              className="mb-1 w-full justify-start truncate text-left text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200 hover:translate-x-1"
              onClick={() => {
                if (window.innerWidth < 768) {
                  setSidebarOpen(false)
                }
              }}
            >
              Understanding quantum computing
            </Button>
            <Button
              variant="ghost"
              className="mb-1 w-full justify-start truncate text-left text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200 hover:translate-x-1"
              onClick={() => {
                if (window.innerWidth < 768) {
                  setSidebarOpen(false)
                }
              }}
            >
              Creative writing prompts
            </Button>

            <div className="mb-2 mt-4 px-2 text-xs font-medium text-secondary/60 dark:text-tertiary/60">Yesterday</div>
            <Button
              variant="ghost"
              className="mb-1 w-full justify-start truncate text-left text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200 hover:translate-x-1"
              onClick={() => {
                if (window.innerWidth < 768) {
                  setSidebarOpen(false)
                }
              }}
            >
              Python code examples
            </Button>
            <Button
              variant="ghost"
              className="mb-1 w-full justify-start truncate text-left text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200 hover:translate-x-1"
              onClick={() => {
                if (window.innerWidth < 768) {
                  setSidebarOpen(false)
                }
              }}
            >
              Travel recommendations
            </Button>
          </div>

          {/* User Section */}
          <div className="border-t border-tertiary dark:border-secondary/20 p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Avatar className="border-2 border-primary transition-all duration-300 hover:scale-110 flex items-center justify-center">
                  <User size={24} className="text-secondary dark:text-tertiary" />
                </Avatar>
                <span className="text-sm font-medium text-secondary dark:text-tertiary">John Doe</span>
              </div>
              <div className="flex gap-1">
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => setShowSettings(true)}
                  className="text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200 hover:scale-105 hover:shadow-lg"
                >
                  <Settings size={18} />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200 hover:scale-105 hover:shadow-lg"
                >
                  <LogOut size={18} />
                </Button>
                <ThemeToggle />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex flex-1 flex-col">
        {/* Header */}
        <header className="flex items-center justify-between border-b border-tertiary dark:border-secondary/20 bg-light-bg dark:bg-dark-bg p-4 transition-colors duration-300">
          <Button
            variant="ghost"
            size="icon"
            className="md:hidden text-secondary dark:text-tertiary hover:bg-primary/10 transition-all duration-200"
            onClick={() => setSidebarOpen(!sidebarOpen)}
          >
            <Menu size={24} />
          </Button>
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary animate-pulse" />
            <span className="font-medium text-secondary dark:text-tertiary">AuraChat</span>
          </div>
          <div className="w-10"></div> {/* Spacer for alignment */}
        </header>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-4">
          <div className="mx-auto max-w-3xl">
            {messages.map((message, index) => (
              <div
                key={message.id}
                className={cn("mb-6 flex", message.role === "user" ? "justify-end" : "justify-start")}
              >
                <div
                  className={cn(
                    "max-w-[80%] rounded-lg p-4 shadow-md transition-shadow duration-300 hover:shadow-lg active:scale-[0.98] cursor-pointer animate-fade-in",
                    message.role === "user"
                      ? "bg-primary text-primary-foreground active:bg-primary/95"
                      : "bg-light-bg dark:bg-muted-dark text-secondary dark:text-tertiary active:bg-tertiary/10 dark:active:bg-muted-dark/90",
                    "after:absolute after:inset-0 after:rounded-lg after:transition-[transform,opacity] after:duration-500 hover:after:scale-[1.02] hover:after:opacity-0 after:opacity-100 after:bg-white/5 relative overflow-hidden",
                  )}
                  style={{ animationDelay: `${index * 50}ms` }}
                  onClick={() => {
                    const ripple = document.createElement("div")
                    ripple.className = "absolute inset-0 bg-white/20 animate-ripple rounded-lg"
                    const target = event?.currentTarget as HTMLElement
                    target.appendChild(ripple)
                    setTimeout(() => ripple.remove(), 1000)

                    // Close sidebar on mobile when clicking a conversation
                    if (window.innerWidth < 768) {
                      setSidebarOpen(false)
                    }
                  }}
                >
                  {renderMessageContent(message)}
                </div>
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>
        </div>

        {/* Input */}
        <div className="border-t border-tertiary dark:border-secondary/20 bg-light-bg dark:bg-dark-bg p-4 transition-colors duration-300">
          <form onSubmit={handleSubmit} className="mx-auto max-w-3xl">
            <div className="mb-4 flex flex-wrap gap-2 justify-center">
              {suggestions.map((suggestion, index) => (
                <button
                  key={suggestion}
                  type="button"
                  onClick={() => setInput(suggestion)}
                  className={cn(
                    "px-3 py-1.5 text-sm rounded-full border border-tertiary/50 dark:border-secondary/30",
                    "bg-light-bg dark:bg-dark-bg text-secondary/70 dark:text-tertiary/70",
                    "hover:border-primary/50 hover:text-primary hover:scale-105",
                    "transition-all duration-200 animate-fade-in",
                  )}
                  style={{ animationDelay: `${index * 50}ms` }}
                >
                  {suggestion}
                </button>
              ))}
            </div>
            <div className="relative">
              <Textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Message AuraChat..."
                className="min-h-[60px] resize-none pr-12 border-tertiary bg-light-bg text-secondary focus:border-primary focus:ring-primary/20 dark:border-secondary/30 dark:bg-dark-bg dark:text-tertiary transition-all duration-200 focus:scale-[1.01]"
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault()
                    handleSubmit(e)
                  }
                }}
              />
              <Button
                type="submit"
                size="icon"
                className="absolute bottom-2 right-2 bg-primary text-primary-foreground hover:bg-primary/90 transition-all duration-300 hover:scale-110 disabled:opacity-50 disabled:hover:scale-100"
                disabled={!input.trim() || isLoading}
              >
                <Send size={18} />
              </Button>
            </div>
            <p className="mt-2 text-center text-xs text-secondary/60 dark:text-tertiary/60">
              AuraChat can make mistakes. Consider checking important information.
            </p>
          </form>
        </div>
      </div>
      {showSettings && <SettingsDialog open={showSettings} onOpenChange={setShowSettings} />}
    </div>
  )
}

